# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fedorovcpp <- function(xpxinv, X, current, complete, iter) {
    .Call('OptimalDesign_fedorovcpp', PACKAGE = 'OptimalDesign', xpxinv, X, current, complete, iter)
}

initDesign <- function(X, design_size) {
    .Call('OptimalDesign_initDesign', PACKAGE = 'OptimalDesign', X, design_size)
}

